# Generated by Django 5.1.6 on 2025-03-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employer', 'Employer'), ('admin', 'Admin'), ('job_seeker', 'Job Seeker')], max_length=20),
        ),
    ]
