# Generated by Django 5.1.6 on 2025-03-07 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('employer', 'Employer'), ('job_seeker', 'Job Seeker')], max_length=20),
        ),
    ]
