# Generated by Django 5.1.6 on 2025-03-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employer',
            options={'ordering': ['user'], 'verbose_name_plural': 'Employers'},
        ),
        migrations.AlterModelOptions(
            name='jobseeker',
            options={'ordering': ['user'], 'verbose_name_plural': 'JobSeekers'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('job_seeker', 'Job Seeker'), ('employer', 'Employer')], max_length=20),
        ),
    ]
