# Generated by Django 5.1.6 on 2025-03-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_employer_options_alter_jobseeker_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employer', 'Employer'), ('job_seeker', 'Job Seeker'), ('admin', 'Admin')], max_length=20),
        ),
    ]
