# Generated by Django 6.0.4 on 2026-04-25 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_initial'),
        ('jobs', '0002_initial'),
        ('resumes', '0002_initial'),
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('job_seeker', 'job'), name='unique_application_per_job'),
        ),
    ]
