# Generated by Django 5.1.6 on 2025-10-27 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['posted_at'], 'verbose_name_plural': 'Jobs'},
        ),
    ]
