# Generated by Django 5.1.6 on 2025-03-04 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_category_options_alter_location_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['title'], 'verbose_name_plural': 'Jobs'},
        ),
    ]
