# Generated by Django 6.0.4 on 2026-04-14 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='jobs.job'),
        ),
        migrations.AddConstraint(
            model_name='analytics',
            constraint=models.UniqueConstraint(fields=('job', 'date'), name='unique_job_date'),
        ),
    ]
