# Generated by Django 5.1.6 on 2025-10-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='analytics',
            constraint=models.UniqueConstraint(fields=('job', 'date'), name='unique_job_date'),
        ),
    ]
