# Generated by Django 5.1.6 on 2025-03-04 21:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('resume_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.FileField(upload_to='resumes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='users.jobseeker')),
            ],
        ),
    ]
