# Generated by Django 5.1.6 on 2025-03-05 16:55

import resumes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file_path',
            field=models.FileField(upload_to='resumes/', validators=[resumes.validators.validate_file_size, resumes.validators.validate_file_extension]),
        ),
    ]
