# Generated by Django 5.1.6 on 2025-03-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_alter_resume_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='checksum',
            field=models.CharField(default=1, max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
