# Generated by Django 5.1.6 on 2025-03-06 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_resume_checksum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['resume_id'], 'verbose_name_plural': 'Resumes'},
        ),
    ]
