# Generated by Django 4.2.4 on 2023-08-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='service',
            field=models.CharField(default=2, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='professional',
            name='price',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='professional',
            name='years_of_experience',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
