# Generated by Django 4.2.4 on 2023-08-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0003_alter_professional_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='service',
            field=models.CharField(choices=[('Tutorship', 'Tutorship'), ('Transportation', 'Transportation'), ('Food', 'Food'), ('Cleaning', 'Cleaning')], max_length=64),
        ),
    ]
