# Generated by Django 5.1.6 on 2025-03-07 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name'], 'verbose_name_plural': 'Skills'},
        ),
    ]
